### PR TITLE
[v2.0] Update help to comply with 2.0 version of X584

### PR DESCRIPTION
**Pull request by danil-kondr2016**

### CODE REVIEW

**Comment by kodemeister** [comment]
Perfect! I just thought about updating the help :grin: 

The updated screenshots look nice but there is a small issue. They have numeric annotations (1, 2, 3...) directly baked into the image. If someone else decides to add new UI controls and update screenshots, they will have to redraw all annotations from scratch. This is boring and tedious work.

Could you please draw images in some opensource vector graphics editor and commit them together with exported PNG images? This way, one will be able to open the image in editor, replace the bottom raster "layer", add new annotations if needed and re-export the document to PNG image. I would suggest to use [draw.io](https://www.drawio.com). It runs in browser and very easy to use. Desktop app is also available. I believe we would need the following files:
* `main_window.drawio` + `main_window.png`
* `input_bus.drawio` + `input_bus.png`
* `filters.drawio` + `filters.png`

Let me know if you have better ideas :smile:

**Comment by kodemeister** [comment]
I believe there are a few more things to add :thinking: 

* Document new `input` (`ввод`) control flow operator.
* Maybe mention Enter shortcuts in different places (code tree view, registers, input bus dialog)?

**Comment by danil-kondr2016** [comment]
Done

**Comment by kodemeister** [comment]
Looks fine, merged :+1:

**Pull request merged**
